# basic options
title: Welcome To My Website
author: Haikun Zhan
email: h.zhan@student.unimelb.edu.au
description: A wonderful site
twitter_username: zhan_charlotte


# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
